import { PrismaClient, InterviewStatus } from "@prisma/client";

const prisma = new PrismaClient();

const USER_ID = "cb00b61a-1ee1-4160-97cb-dd73b01aff66";

// Lista de empresas tech
const companies = [
  "Google",
  "Meta",
  "Amazon",
  "Microsoft",
  "Apple",
  "Netflix",
  "Spotify",
  "Uber",
  "Airbnb",
  "Twitter",
  "LinkedIn",
  "Tesla",
  "Nvidia",
  "Oracle",
  "Salesforce",
  "Adobe",
  "Shopify",
  "Stripe",
  "Twilio",
  "Dropbox",
  "Zoom",
  "Slack",
  "GitHub",
  "Atlassian",
  "Square",
  "Snap",
  "Reddit",
  "Pinterest",
  "Discord",
  "Coinbase",
  "DoorDash",
  "Instacart",
  "Lyft",
  "Robinhood",
  "Notion",
  "Figma",
  "Canva",
  "Databricks",
  "Snowflake",
  "MongoDB",
  "Palantir",
  "Unity",
  "Epic Games",
  "Roblox",
  "Cloudflare",
  "Vercel",
  "Supabase",
  "PlanetScale",
  "Railway",
  "Render",
  "IBM",
  "Intel",
  "AMD",
  "Cisco",
  "Dell",
  "HP",
  "Samsung",
  "LG",
  "Sony",
  "Toshiba",
  "Fujitsu",
  "Hitachi",
  "NEC",
  "Panasonic",
  "Canon",
  "Nikon",
  "PayPal",
  "Visa",
  "Mastercard",
  "Stripe",
  "Square",
  "Klarna",
  "Affirm",
  "Plaid",
  "Brex",
  "Chime",
  "Nubank",
  "Revolut",
  "N26",
  "Monzo",
  "Starling",
  "Wise",
  "TransferWise",
  "Venmo",
  "Cash App",
  "Zelle",
  "WeChat Pay",
  "Alipay",
  "ByteDance",
  "Tencent",
  "Alibaba",
  "Baidu",
  "JD.com",
  "Xiaomi",
  "Huawei",
  "Oppo",
  "Vivo",
  "OnePlus",
  "Realme",
  "Asus",
  "Acer",
  "Lenovo",
  "MSI",
  "Razer",
  "Corsair",
  "Logitech",
  "HyperX",
  "SteelSeries",
  "Alienware",
  "Red Hat",
  "SUSE",
  "Canonical",
  "HashiCorp",
  "GitLab",
  "CircleCI",
  "Jenkins",
  "Docker",
  "Kubernetes",
  "OpenAI",
  "Anthropic",
  "Cohere",
  "Hugging Face",
  "Stability AI",
  "Midjourney",
  "Jasper",
  "Copy.ai",
  "Grammarly",
  "Notion AI",
  "DataRobot",
  "C3.ai",
  "Scale AI",
  "Weights & Biases",
  "Wandb",
  "MLflow",
  "TensorFlow",
  "PyTorch",
  "Keras",
  "Scikit-learn",
  "Pandas",
  "NumPy",
  "Shopee",
  "Mercado Libre",
  "OLX",
  "Carousell",
  "eBay",
  "Etsy",
  "Rakuten",
  "Wayfair",
  "Zillow",
  "Redfin",
  "Compass",
  "OpenDoor",
  "Offerpad",
  "Duolingo",
  "Coursera",
  "Udemy",
  "edX",
  "Khan Academy",
  "Skillshare",
  "Pluralsight",
  "LinkedIn Learning",
  "Udacity",
  "Codecademy",
  "FreeCodeCamp",
  "HackerRank",
  "LeetCode",
  "CodeSignal",
  "Codewars",
  "TopCoder",
  "Codeforces",
  "Peloton",
  "Strava",
  "Zwift",
  "Fitbit",
  "Garmin",
  "Polar",
  "Whoop",
  "TikTok",
  "Snapchat",
  "Instagram",
  "Facebook",
  "WhatsApp",
  "Telegram",
  "Signal",
  "Viber",
  "Line",
  "KakaoTalk",
  "WeChat",
  "QQ",
  "Skype",
  "Teams",
  "Webex",
  "GoToMeeting",
  "BlueJeans",
  "Whereby",
  "Around",
  "Mmhmm",
  "Miro",
  "Mural",
  "Figma",
  "Sketch",
  "Adobe XD",
  "InVision",
  "Framer",
  "Principle",
  "ProtoPie",
  "Origami",
  "Flinto",
  "Marvel",
  "Zeplin",
  "Abstract",
  "ServiceNow",
  "Workday",
  "SAP",
  "Zendesk",
  "Freshworks",
  "HubSpot",
  "Intercom",
  "Drift",
  "LiveChat",
  "Olark",
  "Crisp",
  "Tawk.to",
  "Pure Chat",
  "Asana",
  "Monday.com",
  "Trello",
  "Jira",
  "ClickUp",
  "Basecamp",
  "Wrike",
  "Smartsheet",
  "Airtable",
  "Coda",
  "Roam Research",
  "Obsidian",
  "LogSeq",
  "Todoist",
  "Any.do",
  "Things",
  "OmniFocus",
  "TickTick",
  "Microsoft To Do",
  "Evernote",
  "OneNote",
  "Bear",
  "Simplenote",
  "Standard Notes",
  "Joplin",
  "Twitch",
  "YouTube",
  "Vimeo",
  "Dailymotion",
  "Rumble",
  "Odysee",
  "PeerTube",
  "SoundCloud",
  "Bandcamp",
  "Mixcloud",
  "Audius",
  "Resonate",
  "Audiomack",
  "Pandora",
  "iHeartRadio",
  "Deezer",
  "Tidal",
  "Qobuz",
  "Amazon Music",
  "Apple Music",
  "YouTube Music",
  "SiriusXM",
  "TuneIn",
  "Radio.com",
  "Postman",
  "Insomnia",
  "Paw",
  "RapidAPI",
  "Swagger",
  "Stoplight",
  "Heroku",
  "DigitalOcean",
  "Linode",
  "Vultr",
  "AWS",
  "Azure",
  "GCP",
  "Netlify",
  "Vercel",
  "Cloudflare Pages",
  "GitHub Pages",
  "GitLab Pages",
  "Sentry",
  "Datadog",
  "New Relic",
  "Splunk",
  "LogRocket",
  "FullStory",
  "Hotjar",
  "Mixpanel",
  "Amplitude",
  "Heap",
  "Segment",
  "RudderStack",
  "Auth0",
  "Okta",
  "OneLogin",
  "Ping Identity",
  "ForgeRock",
  "KeyCloak",
  "Stripe",
  "Paddle",
  "Chargebee",
  "Recurly",
  "Zuora",
  "BillFlow",
  "Mailchimp",
  "SendGrid",
  "Twilio SendGrid",
  "Postmark",
  "Amazon SES",
  "ConvertKit",
  "ActiveCampaign",
  "GetResponse",
  "AWeber",
  "MailerLite",
  "Zapier",
  "Make",
  "n8n",
  "Integromat",
  "IFTTT",
  "Automate.io",
  "Workato",
  "Confluent",
  "Apache Kafka",
  "RabbitMQ",
  "Redis",
  "Memcached",
  "Elasticsearch",
  "Algolia",
  "Typesense",
  "Meilisearch",
  "Solr",
  "Lucene",
  "Sphinx",
  "Grafana",
  "Prometheus",
  "InfluxDB",
  "TimescaleDB",
  "Chronograf",
  "Kapacitor",
  "PagerDuty",
  "OpsGenie",
  "VictorOps",
  "xMatters",
  "OnPage",
  "Everbridge",
  "Terraform",
  "Pulumi",
  "Ansible",
  "Chef",
  "Puppet",
  "SaltStack",
  "CloudFormation",
  "ArgoCD",
  "Flux",
  "Spinnaker",
  "Jenkins X",
  "Tekton",
  "Drone",
  "Concourse",
  "Backstage",
  "Port",
  "Kratix",
  "Crossplane",
  "KubeVela",
  "Helm",
  "Kustomize",
  "Istio",
  "Linkerd",
  "Consul",
  "Envoy",
  "NGINX",
  "Traefik",
  "HAProxy",
  "Caddy",
  "Kong",
  "Tyk",
  "Ambassador",
  "Gloo",
  "Contour",
  "Skipper",
  "MinIO",
  "Ceph",
  "GlusterFS",
  "Longhorn",
  "Rook",
  "OpenEBS",
  "Portworx",
  "Cilium",
  "Calico",
  "Weave Net",
  "Flannel",
  "Canal",
  "Antrea",
  "Kube-router",
  "Vault",
  "Sealed Secrets",
  "External Secrets",
  "SOPS",
  "Age",
  "KMS",
  "CockroachDB",
  "YugabyteDB",
  "VoltDB",
  "MemSQL",
  "SingleStore",
  "Vitess",
  "FaunaDB",
  "DynamoDB",
  "Cassandra",
  "ScyllaDB",
  "ArangoDB",
  "Neo4j",
  "DGraph",
  "JanusGraph",
  "TigerGraph",
  "Neptune",
  "OrientDB",
  "Virtuoso",
];

// Cargos variados
const roles = [
  "Software Engineer",
  "Senior Software Engineer",
  "Staff Software Engineer",
  "Principal Engineer",
  "Engineering Manager",
  "Senior Engineering Manager",
  "Frontend Developer",
  "Senior Frontend Developer",
  "Frontend Architect",
  "Backend Developer",
  "Senior Backend Developer",
  "Backend Architect",
  "Full Stack Developer",
  "Senior Full Stack Developer",
  "Full Stack Architect",
  "DevOps Engineer",
  "Senior DevOps Engineer",
  "DevOps Architect",
  "Site Reliability Engineer",
  "Senior SRE",
  "SRE Team Lead",
  "Platform Engineer",
  "Senior Platform Engineer",
  "Platform Architect",
  "Cloud Engineer",
  "Senior Cloud Engineer",
  "Cloud Architect",
  "Data Engineer",
  "Senior Data Engineer",
  "Data Architect",
  "ML Engineer",
  "Senior ML Engineer",
  "ML Architect",
  "AI Engineer",
  "Senior AI Engineer",
  "AI Research Scientist",
  "Mobile Developer",
  "Senior Mobile Developer",
  "Mobile Architect",
  "iOS Developer",
  "Senior iOS Developer",
  "iOS Team Lead",
  "Android Developer",
  "Senior Android Developer",
  "Android Team Lead",
  "React Native Developer",
  "Flutter Developer",
  "Xamarin Developer",
  "QA Engineer",
  "Senior QA Engineer",
  "QA Lead",
  "Test Automation Engineer",
  "SDET",
  "QA Architect",
  "Security Engineer",
  "Senior Security Engineer",
  "Security Architect",
  "Penetration Tester",
  "Security Analyst",
  "Security Consultant",
  "Database Administrator",
  "Senior DBA",
  "Database Architect",
  "Network Engineer",
  "Senior Network Engineer",
  "Network Architect",
  "Systems Engineer",
  "Senior Systems Engineer",
  "Systems Architect",
  "Solutions Architect",
  "Enterprise Architect",
  "Technical Architect",
  "Product Engineer",
  "Technical Product Manager",
  "Engineering Product Manager",
  "Data Scientist",
  "Senior Data Scientist",
  "Lead Data Scientist",
  "Data Analyst",
  "Senior Data Analyst",
  "Analytics Engineer",
  "Business Intelligence Engineer",
  "BI Developer",
  "BI Analyst",
  "Blockchain Developer",
  "Web3 Developer",
  "Smart Contract Developer",
  "Game Developer",
  "Senior Game Developer",
  "Game Engine Developer",
  "Graphics Engineer",
  "Rendering Engineer",
  "VR/AR Engineer",
  "Embedded Engineer",
  "Firmware Engineer",
  "Hardware Engineer",
  "Robotics Engineer",
  "Computer Vision Engineer",
  "NLP Engineer",
  "Research Engineer",
  "Applied Scientist",
  "Research Scientist",
  "Technical Writer",
  "Developer Advocate",
  "Developer Relations Engineer",
  "Solution Engineer",
  "Sales Engineer",
  "Presales Engineer",
  "Support Engineer",
  "Customer Success Engineer",
  "Implementation Engineer",
];

// Descrições variadas
const descriptions = [
  "Building scalable microservices",
  "Working with cloud infrastructure",
  "Developing mobile applications",
  "Creating data pipelines",
  "Machine learning model development",
  "Frontend UI/UX implementation",
  "Backend API development",
  "DevOps automation",
  "Security and compliance",
  "Database optimization",
  "Real-time data processing",
  "Distributed systems",
  "Kubernetes orchestration",
  "CI/CD pipeline management",
  "Performance optimization",
  "System architecture design",
  "GraphQL API development",
  "REST API implementation",
  "Serverless architecture",
  "Event-driven architecture",
  "Legacy system modernization",
  "Technical debt reduction",
  "Monitoring and observability",
  "Infrastructure as code",
  "Container orchestration",
  "Service mesh implementation",
  "API gateway management",
  "Load balancing and caching",
  "Authentication and authorization",
  "Payment processing integration",
  "E-commerce platform development",
  "Content management systems",
  "Search engine optimization",
  "Analytics and reporting",
  "A/B testing infrastructure",
  "Feature flag management",
  "Internationalization support",
  "Accessibility compliance",
  "Progressive web apps",
  "Single page applications",
  "Server-side rendering",
  "Static site generation",
  "Blockchain integration",
  "Cryptocurrency wallet development",
  "Smart contract auditing",
  "NFT marketplace development",
  "DeFi protocol implementation",
  "Gaming engine development",
  "Multiplayer networking",
  "Physics simulation",
  "Procedural generation",
  "AR/VR experiences",
  "Computer vision algorithms",
  "Natural language processing",
  "Recommendation systems",
  "Fraud detection systems",
  "Chatbot development",
  "Voice assistant integration",
  "IoT device integration",
  "Edge computing solutions",
  "Real-time collaboration tools",
  "Video streaming platform",
  "Audio processing pipeline",
  "Image processing algorithms",
  "Document generation system",
  "Workflow automation",
  "ETL pipeline development",
  "Data warehouse management",
  "Business intelligence dashboards",
  "Predictive analytics models",
  "Time series forecasting",
  "Anomaly detection systems",
  "Customer segmentation analysis",
  "Sentiment analysis tools",
  "Knowledge graph construction",
  "Semantic search implementation",
  "Content recommendation engine",
  "Personalization algorithms",
  "Campaign management platform",
  "Marketing automation tools",
  "Customer relationship management",
  "Inventory management system",
  "Supply chain optimization",
  "Logistics tracking platform",
  "Fleet management software",
  "Booking and reservation system",
  "Scheduling and calendar integration",
  "Communication platform",
  "File sharing and collaboration",
  "Version control system",
  "Code review automation",
  "Testing framework development",
  "Bug tracking system",
  "Performance monitoring tools",
  "Error tracking and debugging",
  "Log aggregation and analysis",
  "Metrics collection and visualization",
  "Alerting and incident management",
  "Disaster recovery planning",
  "Backup and restore automation",
];

// Função para gerar data aleatória
function randomDate(start: Date, end: Date): Date {
  return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()));
}

// Função para gerar status aleatório
function randomStatus(): InterviewStatus {
  const statuses = [InterviewStatus.APPROVED, InterviewStatus.PENDING, InterviewStatus.REJECTED];
  return statuses[Math.floor(Math.random() * statuses.length)];
}

// Função para gerar salário aleatório
function randomSalary(): number {
  return Math.floor(Math.random() * (20000 - 5000 + 1) + 5000);
}

async function main() {
  console.log("🌱 Starting seed...");

  // Definir períodos para distribuir as entrevistas
  const periods = [
    { start: new Date("2020-01-01"), end: new Date("2020-12-31"), count: 30 }, // 30 em 2020
    { start: new Date("2021-01-01"), end: new Date("2021-12-31"), count: 40 }, // 40 em 2021
    { start: new Date("2022-01-01"), end: new Date("2022-12-31"), count: 50 }, // 50 em 2022
    { start: new Date("2023-01-01"), end: new Date("2023-12-31"), count: 60 }, // 60 em 2023
    { start: new Date("2024-01-01"), end: new Date("2024-12-31"), count: 100 }, // 100 em 2024
    { start: new Date("2025-01-01"), end: new Date("2025-10-14"), count: 220 }, // 220 em 2025 (mais dados para testar)
  ];

  let totalCreated = 0;

  for (const period of periods) {
    console.log(`📅 Creating ${period.count} interviews for period ${period.start.getFullYear()}...`);

    const interviews: Array<{
      userId: string;
      companyName: string;
      role: string;
      appliedAt: Date;
      salary: number;
      status: InterviewStatus;
      description: string;
    }> = [];

    for (let i = 0; i < period.count; i++) {
      const company = companies[Math.floor(Math.random() * companies.length)];
      const role = roles[Math.floor(Math.random() * roles.length)];
      const description = descriptions[Math.floor(Math.random() * descriptions.length)];
      const appliedAt = randomDate(period.start, period.end);
      const salary = randomSalary();
      const status = randomStatus();

      interviews.push({
        userId: USER_ID,
        companyName: company,
        role,
        appliedAt,
        salary,
        status,
        description,
      });
    }

    // Criar em lote
    await prisma.interview.createMany({
      data: interviews,
      skipDuplicates: true,
    });

    totalCreated += period.count;
    console.log(`✅ Created ${period.count} interviews for ${period.start.getFullYear()}`);
  }

  console.log(`🎉 Seed completed! Total interviews created: ${totalCreated}`);
}

main()
  .catch((e) => {
    console.error("❌ Error seeding database:", e);
    process.exit(1);
  })
  .finally(() => {
    void prisma.$disconnect();
  });
